# Generated by Django 6.0.3 on 2026-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='technical_specializations',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Technical Specializations'),
        ),
    ]
