# Generated by Django 6.0.7 on 2026-09-09 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_technical_specializations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, default='', max_length=255)),
                ('hospital_email', models.EmailField(blank=True, default='', max_length=254)),
                ('hospital_phone', models.CharField(blank=True, default='', max_length=50)),
                ('hospital_address', models.TextField(blank=True, default='')),
                ('min_password_length', models.IntegerField(default=6)),
                ('session_timeout', models.IntegerField(default=60, help_text='Session timeout in minutes')),
                ('require_password_change', models.BooleanField(default=True, help_text='Require newly created users to change password on first login')),
                ('email_notifications', models.BooleanField(default=True, help_text='Master toggle for email notifications')),
                ('vendor_approval_emails', models.BooleanField(default=True)),
                ('vendor_rejection_emails', models.BooleanField(default=True)),
                ('new_user_credential_emails', models.BooleanField(default=True)),
                ('enable_purchase_requisition', models.BooleanField(default=True)),
                ('enable_vendor_quotations', models.BooleanField(default=True)),
                ('enable_purchase_order_processing', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'tbl_system_setting',
            },
        ),
    ]
