# Generated by Django 6.0.3 on 2026-07-30 16:40

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Document Number')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('REQUISITION', 'Requisition'), ('QUOTATION', 'Quotation'), ('PO', 'Purchase Order'), ('INSPECTION', 'Inspection Report'), ('INVOICE', 'Invoice'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('DOCX', 'Word Document'), ('XLSX', 'Excel Spreadsheet'), ('IMAGE', 'Image File'), ('OTHER', 'Other')], default='PDF', max_length=20)),
                ('reference_type', models.CharField(help_text='Target table or module name (e.g. REQUISITION, QUOTATION, INVOICE)', max_length=50)),
                ('reference_id', models.PositiveIntegerField(help_text='Primary Key of referenced record')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'tbl_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
