# Generated by Django 6.0.3 on 2026-08-01 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='reliability_score',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='vendor',
            name='equipment_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='performance_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Vendor Performance Rating / Reliability Score', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active Supplier'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('equipment_category', models.CharField(max_length=100, verbose_name='Medical Equipment Category')),
                ('company_description', models.TextField()),
                ('certificate_file', models.FileField(blank=True, help_text='Business License / Company Registration Certificate', null=True, upload_to='vendor_certificates/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Application',
                'verbose_name_plural': 'Vendor Applications',
                'db_table': 'tbl_vendor_application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendor', to='vendors.vendorapplication'),
        ),
    ]
