# Generated by Django 6.0.3 on 2026-08-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_reliability_score_remove_vendor_tax_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supplier Category',
                'verbose_name_plural': 'Supplier Categories',
                'db_table': 'tbl_supplier_category',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='equipment_category',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='equipment_category',
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='products_services_offered',
            field=models.TextField(blank=True, default='', help_text='Briefly describe the products or services supplied by your company', verbose_name='Products / Services Offered'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='performance_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Vendor Performance Rating', max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Business License / Registration Certificate', null=True, upload_to='vendor_certificates/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='supplier_categories',
            field=models.ManyToManyField(help_text='Multi-select supplier categories', related_name='vendors', to='vendors.suppliercategory'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='supplier_categories',
            field=models.ManyToManyField(help_text='Products or services categories provided by vendor', related_name='applications', to='vendors.suppliercategory'),
        ),
    ]
