# Generated by Django 6.0.7 on 2026-09-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_suppliercategory_remove_vendor_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['id'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterModelOptions(
            name='vendorapplication',
            options={'ordering': ['id'], 'verbose_name': 'Vendor Application', 'verbose_name_plural': 'Vendor Applications'},
        ),
    ]
