# Generated by Django 6.0.7 on 2026-09-08 04:21

from django.db import migrations, models


def standardize_categories(apps, schema_editor):
    SupplierCategory = apps.get_model('vendors', 'SupplierCategory')
    VendorApplication = apps.get_model('vendors', 'VendorApplication')
    Vendor = apps.get_model('vendors', 'Vendor')

    STANDARD_CATEGORIES = [
        {
            'name': 'Medical Equipment & Devices',
            'description': 'Specialized medical instruments, diagnostic machinery, patient monitoring, life-support systems, and therapeutic devices.'
        },
        {
            'name': 'Biomedical Equipment',
            'description': 'Biomedical sensors, calibration meters, safety analyzers, electromedical parts, and life-support test apparatus.'
        },
        {
            'name': 'Medical Consumables',
            'description': 'Disposable medical consumables, syringes, cannulas, gloves, surgical dressings, and sterile supplies.'
        },
        {
            'name': 'Laboratory Equipment & Supplies',
            'description': 'Clinical analyzers, lab reagents, microscopes, centrifuges, glassware, test tubes, and pathology diagnostic tools.'
        },
        {
            'name': 'Surgical Instruments',
            'description': 'Precision surgical instruments, scalpels, forceps, retractors, surgical sets, trays, and sterilizable OR tools.'
        },
        {
            'name': 'Diagnostic Equipment',
            'description': 'Ultrasound systems, ECG/EKG machines, patient vitals monitors, endoscopy sets, and point-of-care diagnostic tools.'
        },
        {
            'name': 'Radiology & Imaging Equipment',
            'description': 'X-ray machines, MRI, CT scanning systems, ultrasound probes, PACS hardware, and radiology imaging accessories.'
        },
        {
            'name': 'ICU & Critical Care Equipment',
            'description': 'Ventilators, syringe and infusion pumps, defibrillators, multipara monitors, and emergency resuscitation gear.'
        },
        {
            'name': 'Hospital Furniture & Fixtures',
            'description': 'Hospital patient beds, examination tables, surgical carts, medical recliners, doctor chairs, and ward cabinets.'
        },
        {
            'name': 'IT Hardware & Software',
            'description': 'Hospital information systems (HIS), workstations, servers, barcode scanners, networking devices, and clinical software.'
        },
        {
            'name': 'Maintenance & Technical Services',
            'description': 'Preventive maintenance contracts, calibration services, biomedical engineering repairs, and equipment overhauls.'
        },
        {
            'name': 'General Hospital Supplies',
            'description': 'Hospital linens, patient gowns, staff scrubs, identification wristbands, catering disposables, and facility sundries.'
        },
        {
            'name': 'Cleaning & Housekeeping Supplies',
            'description': 'Hospital-grade disinfectants, sanitizing chemicals, biohazard disposal bags, janitorial tools, and sterilizing fluids.'
        },
        {
            'name': 'Other',
            'description': 'Other specialized hospital supplies, medical items, and healthcare procurement services not categorized above.'
        },
    ]

    # 1. Create or update canonical categories
    canonical_objs = {}
    for item in STANDARD_CATEGORIES:
        cat, _ = SupplierCategory.objects.get_or_create(
            name=item['name'],
            defaults={'description': item['description']}
        )
        if cat.description != item['description']:
            cat.description = item['description']
            cat.save()
        canonical_objs[item['name']] = cat

    canonical_names = set(canonical_objs.keys())

    # 2. Legacy / duplicate mappings
    LEGACY_MAPPING = {
        'Diagnostic Devices': 'Diagnostic Equipment',
        'Medical Equipment': 'Medical Equipment & Devices',
        'Laboratory Equipment': 'Laboratory Equipment & Supplies',
        'Hospital Furniture': 'Hospital Furniture & Fixtures',
        'Furniture & Fixtures': 'Hospital Furniture & Fixtures',
        'IT & Digital Solutions': 'IT Hardware & Software',
        'Facility & Maintenance Equipment': 'Maintenance & Technical Services',
        'Pharmaceuticals & Medical Consumables': 'Medical Consumables',
        'Office Supplies & Stationery': 'General Hospital Supplies',
    }

    # 3. Remap VendorApplication M2M relations
    for app in VendorApplication.objects.all():
        new_cat_ids = set()
        for cat in app.supplier_categories.all():
            if cat.name in canonical_names:
                new_cat_ids.add(cat.id)
            elif cat.name in LEGACY_MAPPING:
                target_name = LEGACY_MAPPING[cat.name]
                new_cat_ids.add(canonical_objs[target_name].id)
            else:
                new_cat_ids.add(canonical_objs['Other'].id)
        app.supplier_categories.set(new_cat_ids)

    # 4. Remap Vendor M2M relations
    for vendor in Vendor.objects.all():
        new_cat_ids = set()
        for cat in vendor.supplier_categories.all():
            if cat.name in canonical_names:
                new_cat_ids.add(cat.id)
            elif cat.name in LEGACY_MAPPING:
                target_name = LEGACY_MAPPING[cat.name]
                new_cat_ids.add(canonical_objs[target_name].id)
            else:
                new_cat_ids.add(canonical_objs['Other'].id)
        vendor.supplier_categories.set(new_cat_ids)

    # 5. Delete any non-canonical categories
    SupplierCategory.objects.exclude(name__in=canonical_names).delete()


def rollback_categories(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_options_alter_vendorapplication_options'),
    ]

    operations = [
        migrations.RunPython(standardize_categories, rollback_categories),
        migrations.AlterModelOptions(
            name='suppliercategory',
            options={'ordering': ['id'], 'verbose_name': 'Supplier Category', 'verbose_name_plural': 'Supplier Categories'},
        ),
        migrations.AlterField(
            model_name='suppliercategory',
            name='name',
            field=models.CharField(choices=[('Medical Equipment & Devices', 'Medical Equipment & Devices'), ('Biomedical Equipment', 'Biomedical Equipment'), ('Medical Consumables', 'Medical Consumables'), ('Laboratory Equipment & Supplies', 'Laboratory Equipment & Supplies'), ('Surgical Instruments', 'Surgical Instruments'), ('Diagnostic Equipment', 'Diagnostic Equipment'), ('Radiology & Imaging Equipment', 'Radiology & Imaging Equipment'), ('ICU & Critical Care Equipment', 'ICU & Critical Care Equipment'), ('Hospital Furniture & Fixtures', 'Hospital Furniture & Fixtures'), ('IT Hardware & Software', 'IT Hardware & Software'), ('Maintenance & Technical Services', 'Maintenance & Technical Services'), ('General Hospital Supplies', 'General Hospital Supplies'), ('Cleaning & Housekeeping Supplies', 'Cleaning & Housekeeping Supplies'), ('Other', 'Other')], max_length=100, unique=True),
        ),
    ]
