# Generated by Django 6.0.7 on 2026-09-08 05:04

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def repair_approved_vendors(apps, schema_editor):
    VendorApplication = apps.get_model('vendors', 'VendorApplication')
    Vendor = apps.get_model('vendors', 'Vendor')
    User = apps.get_model('accounts', 'User')
    Role = apps.get_model('accounts', 'Role')

    vendor_role, _ = Role.objects.get_or_create(
        name='Vendor',
        defaults={'description': 'Approved Supplier Vendor Account', 'is_active': True}
    )

    # 1. Repair App 3 (MedTech Solutions Pvt. Ltd.)
    app3 = VendorApplication.objects.filter(id=3).first()
    if app3:
        user_ven1001 = User.objects.filter(username='ven_1001').first()
        if not user_ven1001:
            user_ven1001 = User.objects.create(
                username='ven_1001',
                email=app3.email,
                first_name=app3.contact_person,
                role=vendor_role,
                phone=app3.phone,
                is_active=True,
                first_login=False,
                password=make_password('ProcuraMed@2026')
            )

        v3 = Vendor.objects.filter(id=2).first()
        if v3:
            v3.application = app3
            v3.company_name = app3.company_name
            v3.contact_person = app3.contact_person
            v3.email = app3.email
            v3.phone = app3.phone
            v3.vendor_code = 'VEN-2026-00001'
            v3.user = user_ven1001
            v3.status = 'ACTIVE'
            v3.is_active = True
            v3.save()
            v3.supplier_categories.set(app3.supplier_categories.all())

    # 2. Repair App 9 (MedEquip Solutions Pvt. Ltd.)
    app9 = VendorApplication.objects.filter(id=9).first()
    if app9:
        user_ven1002 = User.objects.filter(username='ven_1002').first()
        if not user_ven1002:
            user_ven1002 = User.objects.create(
                username='ven_1002',
                email=app9.email,
                first_name=app9.contact_person,
                role=vendor_role,
                phone=app9.phone,
                is_active=True,
                first_login=True,
                password=make_password('ProcuraMed@2026')
            )

        v9, _ = Vendor.objects.get_or_create(
            application=app9,
            defaults={
                'company_name': app9.company_name,
                'contact_person': app9.contact_person,
                'email': app9.email,
                'phone': app9.phone,
                'vendor_code': 'VEN-2026-00009',
                'user': user_ven1002,
                'status': 'ACTIVE',
                'is_active': True,
            }
        )
        v9.company_name = app9.company_name
        v9.contact_person = app9.contact_person
        v9.email = app9.email
        v9.phone = app9.phone
        v9.vendor_code = 'VEN-2026-00009'
        v9.user = user_ven1002
        v9.status = 'ACTIVE'
        v9.is_active = True
        v9.save()
        v9.supplier_categories.set(app9.supplier_categories.all())

    # 3. For any other approved VendorApplication without a vendor, create one
    for app in VendorApplication.objects.filter(status='APPROVED'):
        has_vendor = Vendor.objects.filter(application=app).exists()
        if not has_vendor:
            v_code = f"VEN-2026-{app.id:04d}"
            base_user = app.email.split('@')[0]
            username = base_user
            c = 1
            while User.objects.filter(username=username).exists():
                username = f"{base_user}_{c}"
                c += 1
            u = User.objects.create(
                username=username,
                email=app.email,
                first_name=app.contact_person,
                role=vendor_role,
                phone=app.phone,
                is_active=True,
                first_login=True,
                password=make_password('ProcuraMed@2026')
            )

            vnd = Vendor.objects.create(
                application=app,
                company_name=app.company_name,
                contact_person=app.contact_person,
                email=app.email,
                phone=app.phone,
                vendor_code=v_code,
                user=u,
                status='ACTIVE',
                is_active=True,
            )
            vnd.supplier_categories.set(app.supplier_categories.all())


def rollback_repair(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_suppliercategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RunPython(repair_approved_vendors, rollback_repair),
    ]
