# Generated by Django 6.0.3 on 2026-07-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Quotation Number'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='RFQ Number'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='req_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Requisition Number'),
        ),
    ]
