# Generated by Django 6.0.7 on 2026-09-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_purchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Item Category / Procurement Domain'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='requires_technical_evaluation',
            field=models.BooleanField(default=False, help_text='Designates whether this procurement item requires technical officer evaluation based on technical complexity.', verbose_name='Requires Technical Evaluation'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='technical_specialization',
            field=models.CharField(blank=True, help_text='One of the 6 approved technical specializations required to evaluate this procurement.', max_length=100, null=True, verbose_name='Required Technical Specialization'),
        ),
    ]
