# Generated by Django 6.0.7 on 2026-09-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_requisition_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='requisitions/documents/', verbose_name='Supporting Document'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RFQ_ISSUED', 'RFQ Issued'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item / Product Name')),
                ('category', models.CharField(blank=True, max_length=150, null=True, verbose_name='Category')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='Specifications')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Estimated Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Price')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Required Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.requisition')),
            ],
            options={
                'verbose_name': 'Requisition Item',
                'verbose_name_plural': 'Requisition Items',
                'db_table': 'tbl_requisition_item',
                'ordering': ['id'],
            },
        ),
    ]
