# Generated by Django 6.0.7 on 2026-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_requisition_review_comments_requisition_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned for Correction'), ('PENDING_TECHNICAL_EVALUATION', 'Pending Technical Evaluation'), ('PENDING_COMMITTEE_REVIEW', 'Pending Committee Review'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RFQ_ISSUED', 'RFQ Issued'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
    ]
