# Generated by Django 6.0.7 on 2026-10-05 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_requisition_submitted_at_alter_requisition_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigned At'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='assigned_purchase_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Purchase Officer'),
        ),
    ]
